In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,10,(3,4))

In [3]:
arr

array([[9, 5, 1, 7],
       [1, 7, 9, 1],
       [4, 1, 7, 1]])

In [4]:
arr.reshape(6,2)

array([[9, 5],
       [1, 7],
       [1, 7],
       [9, 1],
       [4, 1],
       [7, 1]])

In [5]:
arr.reshape(2,6)

array([[9, 5, 1, 7, 1, 7],
       [9, 1, 4, 1, 7, 1]])

In [6]:
arr.T

array([[9, 1, 4],
       [5, 7, 1],
       [1, 9, 7],
       [7, 1, 1]])

In [7]:
arr

array([[9, 5, 1, 7],
       [1, 7, 9, 1],
       [4, 1, 7, 1]])

In [8]:
arr.flatten()

array([9, 5, 1, 7, 1, 7, 9, 1, 4, 1, 7, 1])

In [9]:
arr1=np.array([1,2,3,4])

In [10]:
arr1.ndim

1

In [11]:
arr1

array([1, 2, 3, 4])

In [12]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [13]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4]])

In [14]:
arr

array([[9, 5, 1, 7],
       [1, 7, 9, 1],
       [4, 1, 7, 1]])

In [15]:
np.squeeze(arr)

array([[9, 5, 1, 7],
       [1, 7, 9, 1],
       [4, 1, 7, 1]])

In [16]:
data=np.array([[1],[2],[3]])

In [17]:
data

array([[1],
       [2],
       [3]])

In [18]:
np.squeeze(data)

array([1, 2, 3])

In [19]:
arr1

array([1, 2, 3, 4])

In [20]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [22]:
np.roll(arr1,shift=2)

array([3, 4, 1, 2])

In [23]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
#Numpy Binary Operation

In [25]:
arr1=np.random.randint(1,10,(3,4))

In [26]:
arr2=np.random.randint(1,10,(3,4))

In [27]:
arr1

array([[8, 2, 7, 3],
       [5, 6, 2, 3],
       [2, 6, 9, 1]])

In [28]:
arr2

array([[6, 1, 8, 5],
       [1, 1, 5, 1],
       [1, 2, 5, 6]])

In [29]:
arr1+arr2

array([[14,  3, 15,  8],
       [ 6,  7,  7,  4],
       [ 3,  8, 14,  7]])

In [30]:
arr1*arr2

array([[48,  2, 56, 15],
       [ 5,  6, 10,  3],
       [ 2, 12, 45,  6]])

In [31]:
arr1/arr2

array([[1.33333333, 2.        , 0.875     , 0.6       ],
       [5.        , 6.        , 0.4       , 3.        ],
       [2.        , 3.        , 1.8       , 0.16666667]])

In [32]:
arr1-arr2

array([[ 2,  1, -1, -2],
       [ 4,  5, -3,  2],
       [ 1,  4,  4, -5]])

In [33]:
arr1%arr2

array([[2, 0, 7, 3],
       [0, 0, 2, 0],
       [0, 0, 4, 1]])

In [34]:
arr1**arr2

array([[ 262144,       2, 5764801,     243],
       [      5,       6,      32,       3],
       [      2,      36,   59049,       1]])

In [35]:
arr1&arr2

array([[0, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 2, 1, 0]])

In [36]:
~arr1

array([[ -9,  -3,  -8,  -4],
       [ -6,  -7,  -3,  -4],
       [ -3,  -7, -10,  -2]])

In [37]:
arr1|arr2

array([[14,  3, 15,  7],
       [ 5,  7,  7,  3],
       [ 3,  6, 13,  7]])

In [38]:
arr1>arr2

array([[ True,  True, False, False],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [39]:
#Numpy String Function

In [40]:
arr=np.array(['amar','kumar'])

In [41]:
arr

array(['amar', 'kumar'], dtype='<U5')

In [42]:
np.char.upper(arr)

array(['AMAR', 'KUMAR'], dtype='<U5')

In [43]:
np.char.title(arr)

array(['Amar', 'Kumar'], dtype='<U5')

In [44]:
np.char.capitalize(arr)

array(['Amar', 'Kumar'], dtype='<U5')

In [45]:
#Numpy Mathematical functions

In [46]:
arr1

array([[8, 2, 7, 3],
       [5, 6, 2, 3],
       [2, 6, 9, 1]])

In [48]:
np.sin(arr1)

array([[ 0.98935825,  0.90929743,  0.6569866 ,  0.14112001],
       [-0.95892427, -0.2794155 ,  0.90929743,  0.14112001],
       [ 0.90929743, -0.2794155 ,  0.41211849,  0.84147098]])

In [49]:
np.cos(arr1)

array([[-0.14550003, -0.41614684,  0.75390225, -0.9899925 ],
       [ 0.28366219,  0.96017029, -0.41614684, -0.9899925 ],
       [-0.41614684,  0.96017029, -0.91113026,  0.54030231]])

In [50]:
np.tan(arr1)

array([[-6.79971146, -2.18503986,  0.87144798, -0.14254654],
       [-3.38051501, -0.29100619, -2.18503986, -0.14254654],
       [-2.18503986, -0.29100619, -0.45231566,  1.55740772]])

In [51]:
np.tanh(arr1)

array([[0.99999977, 0.96402758, 0.99999834, 0.99505475],
       [0.9999092 , 0.99998771, 0.96402758, 0.99505475],
       [0.96402758, 0.99998771, 0.99999997, 0.76159416]])

In [52]:
np.log(arr1)

array([[2.07944154, 0.69314718, 1.94591015, 1.09861229],
       [1.60943791, 1.79175947, 0.69314718, 1.09861229],
       [0.69314718, 1.79175947, 2.19722458, 0.        ]])

In [53]:
np.exp(arr1)

array([[2.98095799e+03, 7.38905610e+00, 1.09663316e+03, 2.00855369e+01],
       [1.48413159e+02, 4.03428793e+02, 7.38905610e+00, 2.00855369e+01],
       [7.38905610e+00, 4.03428793e+02, 8.10308393e+03, 2.71828183e+00]])

In [54]:
np.sqrt(arr1)

array([[2.82842712, 1.41421356, 2.64575131, 1.73205081],
       [2.23606798, 2.44948974, 1.41421356, 1.73205081],
       [1.41421356, 2.44948974, 3.        , 1.        ]])

In [57]:
np.power(arr1,2)

array([[64,  4, 49,  9],
       [25, 36,  4,  9],
       [ 4, 36, 81,  1]])

In [58]:
np.mean(arr1)

4.5

In [59]:
np.median(arr1)

4.0

In [60]:
np.std(arr1)

2.565800719723442

In [61]:
np.var(arr1)

6.583333333333333

In [63]:
np.min(arr1)

1

In [64]:
np.max(arr1)

9