In [2]:
#Sort,Search & Counting Functions

In [1]:
import numpy as np

In [5]:
arr=np.array([4,3,6,7,5,4,6,7,0,9])

In [6]:
arr

array([4, 3, 6, 7, 5, 4, 6, 7, 0, 9])

In [7]:
np.sort(arr)

array([0, 3, 4, 4, 5, 6, 6, 7, 7, 9])

In [8]:
np.searchsorted(arr,34)

10

In [9]:
arr1=np.array([0,345,454,0,0,0])

In [10]:
np.count_nonzero(arr1)

2

In [11]:
arr

array([4, 3, 6, 7, 5, 4, 6, 7, 0, 9])

In [12]:
np.where(arr>6)

(array([3, 7, 9]),)

In [13]:
np.extract(arr>6,arr)

array([7, 7, 9])

In [14]:
#Numpy Byte Swapping

In [15]:
arr

array([4, 3, 6, 7, 5, 4, 6, 7, 0, 9])

In [16]:
arr.byteswap()

array([288230376151711744, 216172782113783808, 432345564227567616,
       504403158265495552, 360287970189639680, 288230376151711744,
       432345564227567616, 504403158265495552,                  0,
       648518346341351424])

In [17]:
#Numpy Copies & Views

In [18]:
a=np.copy(arr)

In [19]:
b=arr.view()

In [20]:
b

array([4, 3, 6, 7, 5, 4, 6, 7, 0, 9])

In [21]:
b[0]=67

In [22]:
b

array([67,  3,  6,  7,  5,  4,  6,  7,  0,  9])

In [23]:
a

array([4, 3, 6, 7, 5, 4, 6, 7, 0, 9])

In [24]:
arr

array([67,  3,  6,  7,  5,  4,  6,  7,  0,  9])

In [25]:
#Numpy Matrix Library

In [27]:
import numpy.matlib as nm

In [29]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [30]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [32]:
#Numpy Linear Algebra

In [34]:
arr1=np.random.randint([[2,3],[4,5]])

In [35]:
arr2=np.random.randint([[5,3],[2,5]])

In [36]:
np.dot(arr1,arr2)

array([[6, 3],
       [9, 3]])

In [37]:
arr1@arr2

array([[6, 3],
       [9, 3]])