In [2]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [4]:
ar=np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(l)

array([1, 2, 3, 4])

In [10]:
a=[2,3,4]

In [11]:
np.asanyarray(a)

array([2, 3, 4])

In [13]:
b=np.matrix(l)

In [14]:
b

matrix([[1, 2, 3, 4]])

In [15]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [16]:
a=np.array(l)

In [17]:
a

array([1, 2, 3, 4])

In [20]:
c=a

In [21]:
c

array([1, 2, 3, 4])

In [22]:
a

array([1, 2, 3, 4])

In [24]:
c[0]=100

In [25]:
c

array([100,   2,   3,   4])

In [26]:
a

array([100,   2,   3,   4])

In [27]:
d=np.copy(a)

In [28]:
d

array([100,   2,   3,   4])

In [29]:
a[1]=400

In [30]:
a

array([100, 400,   3,   4])

In [31]:
d

array([100,   2,   3,   4])

In [32]:
np.fromfunction(lambda i,j: i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
iterable=(i*i for i in range(5))

In [35]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [36]:
np.fromstring('234 456 678 890',sep=' ')

array([234., 456., 678., 890.])

In [37]:
np.fromstring('1,2,3,4',sep=',')

array([1., 2., 3., 4.])

In [38]:
#numpy data types

In [39]:
l=[2,3,4,5,6]

In [40]:
ar=np.array(l)

In [41]:
ar

array([2, 3, 4, 5, 6])

In [42]:
ar.ndim

1

In [43]:
ar2=np.array([[1,2,3,4],[2,3,4,5]])

In [44]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [45]:
ar2.ndim

2

In [46]:
ar.size

5

In [47]:
ar2.size

8

In [48]:
ar.shape

(5,)

In [49]:
ar2.shape

(2, 4)

In [51]:
ar.dtype

dtype('int64')

In [52]:
ar2.dtype

dtype('int64')

In [53]:
ar22=np.array([(1.4,45,45),(23,45,66)])

In [54]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [55]:
ar22.dtype

dtype('float64')

In [57]:
list(range(5))

[0, 1, 2, 3, 4]

In [58]:
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [59]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [61]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [62]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [63]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [65]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [66]:
ar4=np.zeros((3,4,2,3))

In [67]:
ar4.ndim

4

In [68]:
ar4.size

72

In [69]:
ar4.shape

(3, 4, 2, 3)

In [70]:
np.ones(4)

array([1., 1., 1., 1.])

In [71]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [73]:
on=np.ones((2,3,2))

In [74]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [75]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [76]:
np.empty((3,5))

array([[4.6467329e-310, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        6.3240403e-322]])

In [3]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [7]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [9]:
arr=np.random.randn(3,4)

In [10]:
import pandas as pd

In [11]:
pd.DataFrame(arr)

0         1         2         3
0 -0.499667  1.403098 -0.993418  0.844091
1  0.650984  0.418362  1.192933 -0.470721
2 -0.260449 -2.063709 -0.379921 -0.396480

In [12]:
np.random.rand(3,4)

array([[0.60014509, 0.5373811 , 0.11249355, 0.20461852],
       [0.00356384, 0.96473787, 0.32186285, 0.77654539],
       [0.81016524, 0.16716816, 0.95846692, 0.73713823]])

In [16]:
p=np.random.randint(1,110,(300,400))

In [18]:
pd.DataFrame(p).to_csv('test.csv')

In [19]:
arr=np.random.rand(3,4)

In [20]:
arr

array([[0.0629422 , 0.74733183, 0.38290514, 0.5962116 ],
       [0.06615395, 0.92884664, 0.13937708, 0.41373348],
       [0.89192215, 0.0872328 , 0.62487313, 0.23815472]])

In [21]:
arr.reshape(6,2)

array([[0.0629422 , 0.74733183],
       [0.38290514, 0.5962116 ],
       [0.06615395, 0.92884664],
       [0.13937708, 0.41373348],
       [0.89192215, 0.0872328 ],
       [0.62487313, 0.23815472]])

In [23]:
arr1=arr.reshape(6,-2)

In [25]:
arr1

array([[0.0629422 , 0.74733183],
       [0.38290514, 0.5962116 ],
       [0.06615395, 0.92884664],
       [0.13937708, 0.41373348],
       [0.89192215, 0.0872328 ],
       [0.62487313, 0.23815472]])

In [27]:
arr1[1][1]

0.5962116038061113

In [30]:
arr1[2:5,1]

array([0.92884664, 0.41373348, 0.0872328 ])

In [32]:
arr=np.random.randint(1,100,(5,5))

In [33]:
arr

array([[58, 90, 44, 44, 26],
       [27, 22, 73, 38, 70],
       [18, 34,  7, 98, 30],
       [15, 70, 34, 91, 62],
       [24, 38, 75, 70, 65]])

In [34]:
arr>50

array([[ True,  True, False, False, False],
       [False, False,  True, False,  True],
       [False, False, False,  True, False],
       [False,  True, False,  True,  True],
       [False, False,  True,  True,  True]])

In [37]:
arr[arr>50]

array([58, 90, 73, 70, 98, 70, 91, 62, 75, 70, 65])

In [38]:
arr

array([[58, 90, 44, 44, 26],
       [27, 22, 73, 38, 70],
       [18, 34,  7, 98, 30],
       [15, 70, 34, 91, 62],
       [24, 38, 75, 70, 65]])

In [40]:
arr[2:4,[1,2]]

array([[34,  7],
       [70, 34]])

In [42]:
arr[0][0]=5000

In [43]:
arr

array([[5000,   90,   44,   44,   26],
       [  27,   22,   73,   38,   70],
       [  18,   34,    7,   98,   30],
       [  15,   70,   34,   91,   62],
       [  24,   38,   75,   70,   65]])

In [44]:
arr1=np.random.randint(1,3,(3,3))

In [46]:
arr2=np.random.randint(1,3,(3,3))

In [47]:
arr1

array([[2, 1, 1],
       [1, 2, 2],
       [2, 1, 2]])

In [48]:
arr2

array([[1, 1, 1],
       [1, 1, 2],
       [2, 2, 1]])

In [49]:
arr1+arr2

array([[3, 2, 2],
       [2, 3, 4],
       [4, 3, 3]])

In [50]:
arr1-arr2

array([[ 1,  0,  0],
       [ 0,  1,  0],
       [ 0, -1,  1]])

In [51]:
arr1/arr2

array([[2. , 1. , 1. ],
       [1. , 2. , 1. ],
       [1. , 0.5, 2. ]])

In [52]:
arr1*arr2

array([[2, 1, 1],
       [1, 2, 4],
       [4, 2, 2]])

In [57]:
arr1@arr2

array([[5, 5, 5],
       [7, 7, 7],
       [7, 7, 6]])

In [58]:
arr1/0

/tmp/ipykernel_77/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [59]:
arr1+100

array([[102, 101, 101],
       [101, 102, 102],
       [102, 101, 102]])

In [60]:
arr1**2

array([[4, 1, 1],
       [1, 4, 4],
       [4, 1, 4]])

In [61]:
#Numpy-Broadcasting

In [62]:
arr=np.zeros((4,4))

In [63]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
row=np.array([1,2,3,4])

In [65]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [66]:
row.T

array([1, 2, 3, 4])

In [67]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [68]:
col=np.array([[1,2,3,4]])

In [69]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [70]:
col

array([[1, 2, 3, 4]])

In [72]:
arr+col.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [73]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
arr1=np.random.randint(1,4,(3,4))

In [76]:
arr1

array([[2, 3, 3, 1],
       [2, 2, 3, 3],
       [3, 1, 1, 2]])

In [77]:
np.sqrt(arr1)

array([[1.41421356, 1.73205081, 1.73205081, 1.        ],
       [1.41421356, 1.41421356, 1.73205081, 1.73205081],
       [1.73205081, 1.        , 1.        , 1.41421356]])

In [78]:
np.exp(arr1)

array([[ 7.3890561 , 20.08553692, 20.08553692,  2.71828183],
       [ 7.3890561 ,  7.3890561 , 20.08553692, 20.08553692],
       [20.08553692,  2.71828183,  2.71828183,  7.3890561 ]])

In [79]:
np.log10(arr1)

array([[0.30103   , 0.47712125, 0.47712125, 0.        ],
       [0.30103   , 0.30103   , 0.47712125, 0.47712125],
       [0.47712125, 0.        , 0.        , 0.30103   ]])